### ISSUE TITLE
The contents of the "ontologyZipFiles" files do not conform to onto-viewer requirements

### ISSUE THREAD

**Issue by przemekgradzki** [edmcouncil/ontology-publisher#112]
The contents of the _ontologyZipFiles_ should be sufficient so that the onto-viewer does not need to download additional ontology files (except for external ontologies).

Sample configuration for [FIBO](https://github.com/edmcouncil/fibo) ontology - see [ontology_config.yaml](https://github.com/edmcouncil/fibo/blob/274a69c7cfa5ed313ad72c5d353bea4e1e930e3b/etc/onto-viewer-web-app/config/ontology_config.yaml#L1-L4):
```
ontologies:
  source:
    - url: 'https://spec.edmcouncil.org/fibo/ontology/MetadataFIBO/'
    - url: 'https://spec.edmcouncil.org/fibo/ontology/AboutFIBODev/'
```
